### ISSUE TITLE
大佬有点事情想跟你聊一聊

### ISSUE THREAD

**Issue by makebl** [yecaojiushu/yuedu#1]

**Comment by yecaojiushu** [comment]
怎么合作，具体说说？

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年12月14日 14:08 |
| 收件人 | yecaojiushu/yuedu ***@***.***> |
| 抄送人 | Subscribed ***@***.***> |
| 主题 | [yecaojiushu/yuedu] 大佬有点事情想跟你聊一聊 (Issue #1) |

大佬能不能拉我进群呢？我这边有资源，也有人，咱们合作一下，为广大书友谋福利！企鹅：279437541

**Comment by makebl** [comment]
我这边有个站，都是书友，书源！软件大家都挺喜欢，界面看着舒服，但是bug有很多！怎么反馈呢？加我企鹅
